name: Generate page
on:
  workflow_dispatch:
  repository_dispatch:
    types:
      - trigger-tutorial-sync
      - trigger-document-sync
  pull_request:
  push:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Checkout tutorial repo
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository_owner }}/bpf-developer-tutorial
          ref: main
          path: tutorial

      - name: Checkout main repository eunomia-bpf
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository_owner }}/eunomia-bpf
          ref: master
          path: eunomia-bpf

      - name: Checkout main repository GPTtrace
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository_owner }}/GPTtrace
          ref: main
          path: GPTtrace

      - name: Checkout main repository bpftime
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository_owner }}/bpftime
          ref: master
          path: bpftime

      - name: Change suffix and merge
        run: |
          ./rename.sh
      
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install dependents
        run: |
          pip install mkdocs-material=="9.*" mkdocs-static-i18n=="0.53"
          pip install "mkdocs-material[imaging]"

      - name: Build page
        if: github.event_name == 'pull_request'
        run: |
          mkdocs build -v

      - name: Deploy page
        if: |
          github.event_name == 'repository_dispatch' ||
          github.event_name == 'push' ||
          github.event_name == 'workflow_dispatch'
        run: |
          mkdocs gh-deploy -m "{sha}" --force --ignore-version --no-history
