name: Generate page
on:
  workflow_dispatch:
  repository_dispatch:
    types:
      - trigger-tutorial-sync
      - trigger-document-sync
  pull_request:
  push:
    branches:
      - main
    paths:
      - docs/**
      - material
      - .github/workflows/mkdocs.yml
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main

      - name: build docs
        run:  make

      - name: Build page
        if: github.event_name == 'pull_request'
        run: |
          mkdocs build -v

      - name: Deploy page
        if: github.event_name == 'repository_dispatch'
        run: |
          mkdocs gh-deploy -m "{sha}" --force --ignore-version --no-history
